apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/votre-utilisateur/test-app-k8s.git
    targetRevision: main
    path: overlays/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  
  syncPolicy:
    # Pour prod, on préfère une sync manuelle pour plus de contrôle
    automated:
      prune: false     # Pas de suppression auto en prod
      selfHeal: false  # Pas de correction auto en prod
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
